# Generated by Django 5.2.4 on 2025-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('D_O_B', models.DateField(auto_now=True)),
                ('Birth_time', models.TimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('feedback', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
