# Generated by Django 5.2.4 on 2025-07-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleTable',
        ),
    ]
