# Generated by Django 5.2.4 on 2025-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0002_delete_sampletable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('d_o_b', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
