# Generated by Django 5.2.4 on 2025-07-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_ranksheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranksheet',
            old_name='social_scence',
            new_name='social_science',
        ),
    ]
