# Generated by Django 5.2.4 on 2025-07-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_rename_social_scence_ranksheet_social_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_task', to='Students.student'),
        ),
    ]
